### ISSUE TITLE
mocha stop work with mootools-1.2.4 - #87

### ISSUE THREAD

**Issue by mui-org** [cdotyone/mochaui#27]
Reported by davcaffa, Dec 15, 2009

What steps will reproduce the problem?
1. use the new version of mootools-1.2.4-core.js and
mootools-1.2.4.2-more.js with all features

What is the expected output? What do you see instead?

Mocha don't work correctly
The error in firefox is:

this.fireEvent is not a function
http://localhost/mocha/scripts/source/Utilities/mocha.js.php
Line 1078

What version of MochaUI are you using?
v.0.9.5

On what operating system and with what browser?
Linux, windows xp
opera, firefox, safari

Please provide any additional information below.

Comment 1 by bryancmason, Jan 28, 2010

I fixed the code for mootools 1.2.4, see attached.  Or if you'd like to know the gory
details... I added "Extends: Events, " (without the quotes) to the beginning of line
933 of version 0.9.5 and it works now.

So the patched lines 932-934 now look like:
MochaUI.Window = new Class({
    Extends: Events, options: MochaUI.Windows.windowOptions,
    initialize: function(options){

```
mochaui-cdsi.js
```

135 KB   Download

**Comment by mui-org** [comment]
works fine in current patched MUI version
